apiVersion: v1
kind: Service
metadata:
  name: bind9-dns
  namespace: dns
  annotations:
    metallb.universe.tf/allow-shared-ip: bind9
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  selector:
    app.kubernetes.io/instance: bind9
    app.kubernetes.io/name: bind9
