apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-vip-config
  namespace: kube-system
data:
  config.yaml: |
    vip_interface: "eth0"
    vip_address: "192.168.1.100"
    vip_leaderelection: true
    enable_loadbalancer: true
    port: 6443
    prometheus: false
    annotations: ""
    enableServicesElection: true
    vipSubnet: ""
