apiVersion: v1
kind: Secret
metadata:
  name: zitadel-secrets
  namespace: zitadel
type: Opaque
stringData:
  values.yaml: |
    zitadel:
      existingSecret: zitadel-creds
      # Note: Replace these placeholder values with actual secure values
      # and encrypt this file with SOPS before committing
      masterkey: "${ZITADEL_MASTERKEY}"
      secretConfig:
        Database:
          cockroach:
            User:
              Password: "${ZITADEL_DB_PASSWORD}"
        ExternalSecure: true
        ExternalDomain: "id.hm.hnnl.eu"
        
    database:
      cockroach:
        auth:
          password: "${ZITADEL_DB_PASSWORD}"
          username: "zitadel"
      
    secrets:
      masterkey: "${ZITADEL_MASTERKEY}"
      
    env:
      SECRET_ADMIN_PASSWORD: "${ZITADEL_ADMIN_PASSWORD}"
