apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-with-secrets
  namespace: demo
  labels:
    app: demo-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-secrets
  template:
    metadata:
      labels:
        app: demo-secrets
    spec:
      containers:
      - name: demo
        image: nginx:stable
        ports:
        - containerPort: 80
        env:
        - name: API_USERNAME
          valueFrom:
            secretKeyRef:
              name: demo-credentials
              key: username
        - name: API_PASSWORD
          valueFrom:
            secretKeyRef:
              name: demo-credentials
              key: password
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: demo-credentials
              key: api-key
        volumeMounts:
        - name: config
          mountPath: /app/config.json
          subPath: config.json
      volumes:
      - name: config
        secret:
          secretName: demo-credentials
          items:
          - key: config.json
            path: config.json
