apiVersion: v1
kind: Service
metadata:
  name: zitadel-lb
  namespace: zitadel
  annotations:
    kube-vip.io/loadbalancerIPs: "192.168.1.110"
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 8080
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: zitadel
