apiVersion: v1
kind: Secret
metadata:
  name: zitadel-secrets
  namespace: zitadel
type: Opaque
stringData:
  values.yaml: |
    zitadel:
      existingSecret: zitadel-creds
      masterkey: "master-key-replace-with-secure-value"
      secretConfig:
        Database:
          cockroach:
            User:
              Password: "replace-with-secure-password"
        ExternalSecure: true
        ExternalDomain: "id.homelab.local"
        
    database:
      cockroach:
        auth:
          password: "replace-with-secure-password"
          username: "zitadel"
      
    secrets:
      masterkey: "master-key-replace-with-secure-value"
      
    env:
      SECRET_ADMIN_PASSWORD: "replace-with-secure-admin-password"
