apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-controller
  namespace: flux-system
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: SOPS_AGE_KEY_FILE
          value: /etc/fluxcd/keys/age.agekey
        volumeMounts:
        - name: sops-age
          mountPath: /etc/fluxcd/keys
          readOnly: true
      volumes:
      - name: sops-age
        secret:
          secretName: sops-age
          defaultMode: 0400
