apiVersion: v1
kind: Secret
metadata:
  name: demo-credentials
  namespace: demo
type: Opaque
stringData:
  username: admin
  password: secure-password-here
  api-key: abcdef123456
  config.json: |
    {
      "endpoint": "https://api.example.com",
      "timeout": 30,
      "retries": 3,
      "debug": false
    }
