---
apiVersion: v1
kind: Service
metadata:
  name: cluster-public-ip
  namespace: external-dns
  annotations:
    external-dns.alpha.kubernetes.io/hostname: hm.hnnl.eu
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  type: LoadBalancer
  ports:
    - port: 443
      name: https
      targetPort: 443
      protocol: TCP
    - port: 80
      name: http
      targetPort: 80
      protocol: TCP
  selector:
    app: ingress-nginx
