apiVersion: v1
kind: Secret
metadata:
  name: netbird-management-secrets
  namespace: netbird
type: Opaque
stringData:
  values.yaml: |
    env:
      SECRET_OIDC_CLIENT_ID: "netbird-client-id"
      SECRET_OIDC_CLIENT_SECRET: "replace-with-secure-client-secret"
      JWT_SECRET: "replace-with-secure-jwt-secret"
      
    coturn:
      auth:
        secret: "replace-with-secure-coturn-secret"
