apiVersion: v1
kind: Service
metadata:
  name: access-both
  namespace: dual-access-demo
  annotations:
    external-dns.alpha.kubernetes.io/hostname: both.ext.hm.hnnl.eu, both.local.hm.hnnl.eu
    external-dns.alpha.kubernetes.io/target-type: "both"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: access-demo
